# Default values for salil-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
dbReplicaCount : 1

image:
  repository: salilr/study_app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v54"

imagePullSecrets: 
  - name: dockerhubsalil
service:
  dbType: ClusterIP
  appType: NodePort
  port: 80
  appPort: 5000
  dbPort: 6379
  nodeport: 32000
autoscaling:
  enabled: false
