apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: {{ .Values.service.dbType }}
  ports:
    - port: {{ .Values.service.dbPort }}
      targetPort: {{ .Values.service.dbPort }}
  selector:
    name: redis-pod
    type: db