apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeployment
  labels:
    app: pythonappdeployment
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      name: pythonapp
      type: app
  template:
    metadata:
      name: pythonapp
      labels:
        name: pythonapp
        type: app
    spec:
      containers:
        - name: sampleapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.appPort }}
              name: app-port
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
