apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbdeployment
  labels:
    app: redisdeployment
spec:
  selector:
    matchLabels:
      name: redis-pod
      type: db
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.dbReplicaCount }}
  {{- end }}
  template:
    metadata:
      name: redis
      labels:
        name: redis-pod
        type: db
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            requests:
              memory: "32Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "350m"
          ports:
            - containerPort: {{ .Values.service.dbPort }} #6379
              name: db-port
