apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: {{ .Values.service.appType }}
  ports:
    - targetPort: app-port
      port: {{ .Values.service.appPort }}
      nodePort: {{ .Values.service.nodeport }}
      protocol: TCP
      name: appservice
  selector:
    name: pythonapp
    type: app