apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbdeployment
  labels:
    app: redisdeployment
spec:
  selector:
    matchLabels:
      name: redis-pod
      type: db
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.dbReplicaCount }}
  {{- end }}
  template:
    metadata:
      name: redis
      labels:
        name: redis-pod
        type: db
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            {{- toYaml .Values.resources | nindent 12 }}            
          ports:
            - containerPort: {{ .Values.service.dbPort }} #6379
              name: db-port
        tolerations:
          {{- toYaml .Values.tolerations | nindent 8 }} 
